### ISSUE TITLE
Where is the server ?

### ISSUE THREAD

**Issue by florindumitru** [murugancmi/nari#1]
Hi,
Where can I find the signaling server ?

**Comment by murugancmi** [comment]
you can find nari signalling server here https://github.com/murugancmi/nari-node/tree/master

**Comment by florindum** [comment]
Looks good, but how that server is scalable since I can't find anything related to redis or mqtt to can use it with multiple machines (horizontal scaling and vertical scaling) ?

**Comment by murugancmi** [comment]
you need to add redis adapter in socket.io its very simple just two lines of code ,it will solve your scaling problem

**Comment by murugancmi** [comment]
when i get free time i will add this feature

**Comment by florindum** [comment]
Ok, I'll try. Thanks a lot !

**Comment by florindum** [comment]
Unfortunately the server is not working at all, even if I put the missing code regarding to server variable which missing, the connection never work.

**Comment by florindum** [comment]
I tested with https://websocket.org/echo.html to see if connect

**Comment by murugancmi** [comment]
Please share your server log
